name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli

      - name: Generate parser
        run: tree-sitter generate

      - name: Run tests
        run: tree-sitter test
